src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Entity\user;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LessonRepository")
 */
class Lesson
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="time")
     */
    private $time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="integer", length=255, nullable=true)
     */
    private $max_persons;


    /**
     * @ORM\ManyToOne(targetEntity="training", inversedBy="lessons")
     */
    private $training_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="lesson_id")
     */
    private $registrations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user", inversedBy="lessons")
     */
    private $instructeur;


    public function __construct()
    {
        $this->registrations = new ArrayCollection();
        $this->instructeur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMaxPersons(): ?int
    {
        return $this->max_persons;
    }

    public function setMaxPersons(int $max_persons): self
    {
        $this->max_persons = $max_persons;

        return $this;
    }


    public function getTrainingId(): ?training
    {
        return $this->training_id;
    }

    public function setTrainingId(?training $training_id): self
    {
        $this->training_id = $training_id;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setLessonId($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getLessonId() === $this) {
                $registration->setLessonId(null);
            }
        }

        return $this;
    }

    public function getInstructeur(): ?user
    {
        return $this->instructeur;
    }

    public function setInstructeur(?user $instructeur): self
    {
        $this->instructeur = $instructeur;

        return $this;
    }


}

src/Entity/Registration.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RegistrationRepository")
 */
class Registration
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $payment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\lesson", inversedBy="registrations")
     */
    private $lesson_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user", inversedBy="registrations")
     */
    private $user;


    public function __construct()
    {
        $this->user = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPayment(): ?int
    {
        return $this->payment;
    }

    public function setPayment(?int $payment): self
    {
        $this->payment = $payment;

        return $this;
    }

    public function getLessonId(): ?lesson
    {
        return $this->lesson_id;
    }

    public function setLessonId(?lesson $lesson_id): self
    {
        $this->lesson_id = $lesson_id;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }
//    public function __toString()
//    {
//        // TODO: Implement __toString() method.
//        return $this->
//    }


}

src/Controller/GebruikerController.php
<?php

namespace App\Controller;

use App\Entity\Lesson;
use App\Entity\Registration;
use App\Entity\user;
use App\Form\UserType;
use App\Repository\LessonRepository;
use App\Repository\RegistrationRepository;
use App\Repository\TrainingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/user", name="user")
 */
class GebruikerController extends AbstractController
{
    /**
     * @Route ("/", name="home")
     */
    public function homePage()
    {
        return $this->render('pages/home.html.twig');
    }


    /**
     * @Route("/inschrijven", name="inschrijven")
     */
    public function inschrijvenPage(LessonRepository $lessonRepository, RegistrationRepository $registrationRepository): Response
    {
        return $this->render('gebruiker/inschrijven.html.twig', [
            'lessons' => $lessonRepository->findAll(),
            'registrations' => $registrationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/inschrijvenoverzicht", name="inschrijvenoverzicht")
     */
    public function inschrijvenOverzicht(RegistrationRepository $registrationRepository): Response
    {
        return $this->render('gebruiker/overzichtinschrijven.html.twig', [
            'registrations' => $registrationRepository->findAll(),
        ]);
    }

    /**
 * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
 */
    public function edit(Request $request, user $user, UserPasswordEncoderInterface $encoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $encoded = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($encoded);
            $this->addFlash('success', 'section.backoffice.users.edit_roles.confirmation');
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('userhome');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/inschrijven/{id}" , name="app_nu_inschrijvingen")
     */
    public function inschrijvenLesson($id)
    {
        $les = $this->getDoctrine()
            ->getRepository(Lesson::class)
            ->find($id);

        $user=$this->getUser();

        $registration=new Registration();
        $registration->setLessonId($les);
        $registration->setUser($user);
        $registration->setPayment(false);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($registration);
        $entityManager->flush();

//        return $this->render('pages/home.html.twig', [
//            'page_name' => 'app_latere_inschrijvingen'
//        ]);
        return $this->redirectToRoute('userinschrijven');
    }

    /**
     * @Route("/uitschrijven/{id}", name="lesson_user_delete", methods={"DELETE"})
     */
    public function lesDelete(Request $request, Registration $registration): Response
    {
        if ($this->isCsrfTokenValid('delete'.$registration->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($registration);
            $entityManager->flush();
        }

        return $this->redirectToRoute('userinschrijvenoverzicht');
    }

    /**
     * @Route("/inschrijven/uitschrijven/{id}", name="lesson_user_delete_inschrijven", methods={"DELETE"})
     */
    public function lesDeleteIn(Request $request, Registration $registration): Response
    {
        if ($this->isCsrfTokenValid('delete'.$registration->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($registration);
            $entityManager->flush();
        }

        return $this->redirectToRoute('userinschrijven');
    }
}

templates/gebruiker/inschrijven.html.twig
{% extends 'base.html.twig' %}


{% block content %}

    <br>

    <ul class="nav nav-pills">
        <li class="nav-item">
            <a style="" type="button" class="nav-link btn btn-warning"
               href="#">{{ "now"|format_datetime(pattern="E d LLL", locale='nl')|upper }}</a>
        </li>
        {% for i in 1..15 %}
            <li class="nav-item">
                <a class="nav-link text-dark"
                   href="#">{{ "+#{i}days"|format_datetime(pattern="E d LLL", locale='nl')|upper }}</a>
            </li>
        {% endfor %}
        <li class="nav-item">
            <a class="nav-link text-dark" href="#">LATER</a>
        </li>
    </ul>
    <br>
    <br>

    <div class="table-responsive">
        <table class="table table-bordered" style="text-align: center">
            <thead>
            <tr>
                <th>Tijd</th>
                <th>Foto</th>
                <th>Sport</th>
                <th>Aantal ingeschreven deelnemers</th>
                <th>Prijs (EUR)</th>
                <th>Beschrijving</th>
                <th>Inschrijven</th>
            </tr>
            </thead>
            <tbody>
            {% for lesson in lessons %}
                <tr>
                    <td>{{ lesson.time ? lesson.time|date('H:i') : '' }}</td>
                    <td><img class="img-fluid rounded "
                             src="{{ asset('uploads/brochures/' ~ lesson.trainingId.BrochureFilename) }}"
                             alt="" style="height: 200px"></td>
                    <td>{{ lesson.trainingId.naam }}</td>
                    <td>{{ lesson.registrations|length }}/{{ lesson.maxPersons }}</td>
                    <td>{{ lesson.trainingId.costs }}</td>
                    <td>{{ lesson.trainingId.description }}</td>

                    {% set used = 'false' %}
                    {% for registration in lesson.registrations %}
                        {% if registration.user.id == app.user.id %}
                            <td>
                                <form class="d-inline" method="post" action="{{ path('userlesson_user_delete_inschrijven', {'id': registration.id}) }}" onsubmit="return confirm('Weet je zeker dat je wilt uitschrijven?');">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ registration.id) }}">
                                    <button style="width: 120px;" class="btn btn-outline-danger d-inline">
                                        <span class="replies">Ingeschreven</span>
                                        <span class="comment">Uitschrijven</span>
                                    </button>
                                </form>
                            </td>
                            {% set used = 'true' %}
                        {% endif %}
                    {% endfor %}
                    {% if lesson.registrations|length < lesson.maxPersons and used == 'false' %}
                        <td><a style="width: 120px;"  type="button" class="btn btn-outline-success"
                               href="/user/inschrijven/{{ lesson.id }}">Inschrijven</a>
                        </td>
                    {% elseif used == 'false' %}
                        <td>
                            <button  style="width: 120px;"  class="btn btn-outline-danger">Vol</button>
                        </td>
                    {% endif %}
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <style>
        button .comment { display: none; }
        button:hover .replies { display: none; }
        button:hover .comment { display: inline; }
    </style>
{% endblock %}

templates/gebruiker/overzichtinschrijven.html.twig
{% extends 'base.html.twig' %}


{% block content %}

    <br>

    <div class="table-responsive">
        <table class="table table-bordered" style="text-align: center">
            <thead>
            <tr>
                <th>Datum</th>
                <th>Tijd</th>
                <th>Sport</th>
                <th>Aantal ingeschreven deelnemers</th>
                <th>Prijs (EUR)</th>
                <th>Uitschrijven</th>
            </tr>
            </thead>
            <tbody>
            {% for registration in registrations %}
                {% if registration.user.id == app.user.id %}
                <tr>

                    <td>{{ registration.lessonId.date  ? registration.lessonId.date|date('Y-m-d') : '' }}</td>
                    <td>{{ registration.lessonId.time  ? registration.lessonId.time|date('H:i') : '' }}</td>
                    <td>{{ registration.lessonId.trainingId.naam }}</td>
                    <td>{{ registration.lessonId.registrations|length }}</td>
                    <td>{{ registration.lessonId.trainingId.costs }}</td>
                    <td><form class="d-inline" method="post" action="{{ path('userlesson_user_delete', {'id': registration.id}) }}" onsubmit="return confirm('Weet je zeker dat je wilt uitschrijven?');">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ registration.id) }}">
                            <button class="btn btn-outline-danger d-inline">Uitschrijven</button>
                        </form></td>

{#                    <td><img class="img-fluid rounded " src="{{ asset('uploads/brochures/' ~ lesson.trainingId.BrochureFilename) }}" alt=""></td>#}
{#                    <td>{{ lesson.trainingId.naam }}</td>#}
{#                    <td>{{ lesson.maxPersons }}</td>#}
{#                    <td>{{ lesson.trainingId.costs }}</td>#}
{#                    <td>{{ lesson.trainingId.description }}</td>#}
{#                    <td><a type="button" class="btn btn-outline-success" href="/user/inschrijven/{{ lesson.id }}">Inschrijven</a></td>#}

                </tr>
                {% elseif registration.user.id != app.user.id %}
                    {% else %}
                    <tr>
                        <td colspan="6">no records found</td>
                    </tr>
                    {% endif %}
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}