src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Entity\user;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LessonRepository")
 */
class Lesson
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="time")
     */
    private $time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="integer", length=255, nullable=true)
     */
    private $max_persons;


    /**
     * @ORM\ManyToOne(targetEntity="training", inversedBy="lessons")
     */
    private $training_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="lesson_id")
     */
    private $registrations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user", inversedBy="lessons")
     */
    private $instructeur;


    public function __construct()
    {
        $this->registrations = new ArrayCollection();
        $this->instructeur = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMaxPersons(): ?int
    {
        return $this->max_persons;
    }

    public function setMaxPersons(int $max_persons): self
    {
        $this->max_persons = $max_persons;

        return $this;
    }


    public function getTrainingId(): ?training
    {
        return $this->training_id;
    }

    public function setTrainingId(?training $training_id): self
    {
        $this->training_id = $training_id;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setLessonId($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getLessonId() === $this) {
                $registration->setLessonId(null);
            }
        }

        return $this;
    }

    public function getInstructeur(): ?user
    {
        return $this->instructeur;
    }

    public function setInstructeur(?user $instructeur): self
    {
        $this->instructeur = $instructeur;

        return $this;
    }


}

src/Entity/Registration.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RegistrationRepository")
 */
class Registration
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $payment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\lesson", inversedBy="registrations")
     */
    private $lesson_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user", inversedBy="registrations")
     */
    private $user;


    public function __construct()
    {
        $this->user = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPayment(): ?int
    {
        return $this->payment;
    }

    public function setPayment(?int $payment): self
    {
        $this->payment = $payment;

        return $this;
    }

    public function getLessonId(): ?lesson
    {
        return $this->lesson_id;
    }

    public function setLessonId(?lesson $lesson_id): self
    {
        $this->lesson_id = $lesson_id;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }
//    public function __toString()
//    {
//        // TODO: Implement __toString() method.
//        return $this->
//    }


}

src/Entity/user.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class user implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $loginname;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $preprovision;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date")
     */
    private $dateofbirth;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hiring_date;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $salary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $place;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Lesson", mappedBy="instructeur")
     */
    private $lessons;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="user")
     */
    private $registrations;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;




    public function __construct()
    {
        $this->lessons = new ArrayCollection();
        $this->registrations = new ArrayCollection();
        $this->training = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLoginname(): ?string
    {
        return $this->loginname;
    }

    public function setLoginname(string $loginname): self
    {
        $this->loginname = $loginname;

        return $this;
    }

    public function getPreprovision(): ?string
    {
        return $this->preprovision;
    }

    public function setPreprovision(string $preprovision): self
    {
        $this->preprovision = $preprovision;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDateofbirth(): ?\DateTimeInterface
    {
        return $this->dateofbirth;
    }

    public function setDateofbirth(?\DateTimeInterface $dateofbirth): self
    {
        $this->dateofbirth = $dateofbirth;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getHiringDate(): ?string
    {
        return $this->hiring_date;
    }

    public function setHiringDate(string $hiring_date): self
    {
        $this->hiring_date = $hiring_date;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(string $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(?string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(?string $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
//        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * @return Collection|Lesson[]
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons[] = $lesson;
            $lesson->setInstructeur($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->contains($lesson)) {
            $this->lessons->removeElement($lesson);
            // set the owning side to null (unless already changed)
            if ($lesson->getInstructeur() === $this) {
                $lesson->setInstructeur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setUser($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getUser() === $this) {
                $registration->setUser(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }




}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\user;
use Doctrine\DBAL\Types\StringType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\DateTime;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('loginname', TextType::class ,[
                'label'=> 'Login naam',
            ])
            ->add('password', PasswordType::class, [
                'label'=> 'Wachtwoord',
            ])
            ->add('firstname', TextType::class ,[
                'label'=> 'Voornaam',
            ])
            ->add('preprovision', TextType::class ,[
                'label'=> 'Tussenvoegsel',
                'required' => false,
            ])
            ->add('lastname', TextType::class ,[
                'label'=> 'Achternaam',
            ])
            ->add('dateofbirth', BirthdayType::class, [
                // this is actually the default format for single_text
                'format' => 'dd-MM-yyyy',
                'label'=> 'Geboortedatum',
            ])
            ->add('street', TextType::class ,[
                'label'=> 'Straat',
            ])
            ->add('postal_code', TextType::class ,[
                'label'=> 'Postcode',
            ])
            ->add('place', TextType::class ,[
                'label'=> 'Plaats',
            ])
            ->add('gender', ChoiceType::class, [
                'choices' => [
                    'Man' => 'Man',
                    'Vrouw' => 'Vrouw',
                ],
                'label'=> 'Geslacht',
            ]);;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => user::class,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form class="d-inline" method="post" action="{{ path('adminuser_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-outline-danger d-inline">Verwijder</button>
</form>

templates/user/_form.html.twig
<div class="d-inline">
    {{ form_start(form) }}
</div>
    {{ form_widget(form) }}
    {% if is_granted('ROLE_ADMIN') %}
        {% if app.request.get('_route') == 'adminuser_new' %}
            <a type="button" class="btn btn-outline-success"
               href="{{ path('adminuser_index') }}">terug</a>
        {% elseif app.request.get('_route') == 'admininstructeur_new' %}
            <a type="button" class="btn btn-outline-success"
               href="{{ path('admininstructeurs') }}">terug</a>
        {% elseif app.request.get('_route') == 'adminuser_edit' %}
            <a type="button" class="btn btn-outline-success"
               href="{{ path('admininstructeurs') }}">terug</a>
        {% endif %}
    {% endif %}
    <button class="btn btn-outline-warning ">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
    {% if app.request.get('_route') != 'adminuser_new' and app.request.get('_route') != 'lidworden' and app.request.get('_route') != 'admininstructeur_new' and app.request.get('_route') != 'useruser_edit' and app.request.get('_route') != 'instructeuruser_edit' %}
        {{ include('user/_delete_form.html.twig') }}
    {% endif %}

templates/user/disable-enable.html.twig
{% if user.status == true %}
    <form class="d-inline" method="post" action="{% if user.roles  == ['ROLE_USER'] %}{{ path('adminuser_disable', {'id': user.id}) }}{% elseif user.roles  == ['ROLE_INSTRUCTEUR'] %} {{ path('admininstructeur_disable', {'id': user.id}) }} {% endif %}" onsubmit="return confirm('Weet je zeker dat je de klant wilt uitzetten?');">
        <input type="hidden" name="_method" value="DISABLE">
        <button class="btn btn-outline-danger d-inline">Uitzetten</button>
    </form>
{% else %}
    <form class="d-inline" method="post" action="{% if user.roles  == ['ROLE_USER'] %}{{ path('adminuser_enable', {'id': user.id}) }}{% elseif user.roles  == ['ROLE_INSTRUCTEUR'] %} {{ path('admininstructeur_enable', {'id': user.id}) }} {% endif %}" onsubmit="return confirm('Weet je zeker dat je de klant wilt aanzetten?');">
        <input type="hidden" name="_method" value="ENABLE">
        <button class="btn btn-outline-success d-inline">Aanzetten</button>
    </form>
{% endif %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}


{% block content %}
    <h1>Edit Gebruiker</h1>

    {% if "ROLE_USER" in app.user.roles or "ROLE_INSTRUCTEUR" in app.user.roles %}
        {% if app.user.id == user.id %}
            {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
        {% elseif "ROLE_INSTRUCTEUR" in app.user.roles %}
            <h3>Hier hoort u niet ga terug:</h3>
            <a class="btn btn-outline-warning" href="/instructeur/{{ app.user.id }}/edit">Terug</a>
        {% elseif "ROLE_USER" in app.user.roles %}
            <h3>Hier hoort u niet ga terug:</h3>
            <a class="btn btn-outline-warning" href="/user/{{ app.user.id }}/edit">Terug</a>
        {% endif %}
    {% else %}
        {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
    {% endif %}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <h1>Gebruiker overzicht</h1>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Email</th>
                    <th>Loginname</th>
                    <th>Eerstenaam</th>
                    <th>Tussen voegsel</th>
                    <th>Achternaam</th>
                    <th>Acties</th>
                </tr>
            </thead>
            <tbody>

            {% for user in users %}
                {% if "ROLE_USER" in user.roles and app.request.get('_route') == 'adminuser_index' %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.loginname }}</td>
                        <td>{{ user.firstname }}</td>
                        <td>{{ user.preprovision }}</td>
                        <td>{{ user.lastname }}</td>
                        <td>
                            <a type="button" class="btn btn-outline-success"
                               href="{{ path('adminuser_show', {'id': user.id}) }}">show</a>
                            <a type="button" class="btn btn-outline-warning"
                               href="{{ path('adminuser_edit', {'id': user.id}) }}">edit</a>
                            {{ include('user/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {%  elseif "ROLE_INSTRUCTEUR" in user.roles and app.request.get('_route') == 'admininstructeurs' %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.loginname }}</td>
                        <td>{{ user.firstname }}</td>
                        <td>{{ user.preprovision }}</td>
                        <td>{{ user.lastname }}</td>
                        <td>
                            <a type="button" class="btn btn-outline-success"
                               href="{{ path('adminuser_show', {'id': user.id}) }}">show</a>
                            <a type="button" class="btn btn-outline-warning"
                               href="{{ path('adminuser_edit', {'id': user.id}) }}">edit</a>
                            {{ include('user/_delete_form.html.twig') }}
                        </td>
                    </tr>
                {% endif %}
            {% else %}
                <tr>
                    <td colspan="6">Geen User's Gevonden</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
        {% if app.request.get('_route') == 'adminuser_index' %}
            <a type="button" class="btn btn-outline-success"
               href="{{ path('adminuser_new') }}">Aanmaken</a>
        {%  elseif app.request.get('_route') == 'admininstructeurs' %}
            <a type="button" class="btn btn-outline-success"
               href="{{ path('admininstructeur_new') }}">Aanmaken</a>
        {% endif %}
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}


{% block content %}
    <h1>Gebruiker aanmaken</h1>

    {{ include('user/_form.html.twig') }}



{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}


{% block content %}
    <h1>Gebruiker</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ user.id }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Loginname</th>
            <td>{{ user.loginname }}</td>
        </tr>
        <tr>
            <th>Firstname</th>
            <td>{{ user.firstname }}</td>
        </tr>
        <tr>
            <th>Preprovision</th>
            <td>{{ user.preprovision }}</td>
        </tr>
        <tr>
            <th>Lastname</th>
            <td>{{ user.lastname }}</td>
        </tr>
        <tr>
            <th>Dateofbirth</th>
            <td>{{ user.dateofbirth  ? user.dateofbirth|date('d-m-Y') : '' }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>{{ user.gender }}</td>
        </tr>
        <tr>
            <th>Hiring_date</th>
            <td>{{ user.hiringDate }}</td>
        </tr>
        <tr>
            <th>Salary</th>
            <td>{{ user.salary }}</td>
        </tr>
        <tr>
            <th>Street</th>
            <td>{{ user.street }}</td>
        </tr>
        <tr>
            <th>Postal_code</th>
            <td>{{ user.postalCode }}</td>
        </tr>
        <tr>
            <th>Place</th>
            <td>{{ user.place }}</td>
        </tr>
        <tr>
            <th>Roles</th>
            <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
        </tr>
        {% if user.roles == ['ROLE_INSTRUCTEUR'] %}
        <tr>
            <th>Omzet</th>
            <td>
                {% set omzet = 0.00 %}
                {% for registration in registrations %}
                    {% if registration.lessonId.instructeur.id == user.id %}
                        {% if registration.payment == true %}
                            {% set omzet = omzet + registration.lessonId.trainingId.costs %}
                        {% endif %}
                    {% endif %}
                {% endfor %}
                €{{ omzet }}
            </td>
        </tr>
        {% endif %}
        <tr>
            <th>Aanzetten/Uitzetten</th>
            <td>{{ include('user/disable-enable.html.twig') }}</td>
        </tr>
        </tbody>
    </table>

    <table class="table table-bordered" style="text-align: center">
        <thead>
        <tr>
            <th>Datum</th>
            <th>Tijd</th>
            <th>Zaal</th>
            <th>Sport</th>
            {% if user.roles != ['ROLE_INSTRUCTEUR'] %}
                <th>Prijs (EUR)</th>
                <th>Betaald</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
            {% if user.roles  == ['ROLE_INSTRUCTEUR'] %}
                {% for lesson in lessons %}
                    {% if lesson.instructeur.id == user.id %}
                        <tr>
                            <td>{{ lesson.date  ? lesson.date|date('Y-m-d') : '' }}</td>
                            <td>{{ lesson.time  ? lesson.time|date('H:i') : '' }}</td>
                            <td>{{ lesson.location }}</td>
                            <td>{{ lesson.trainingId.naam }}</td>
                        </tr>
                    {% elseif lesson.instructeur.id != app.user.id %}
                    {% else %}
                        <tr>
                            <td colspan="4">Niks gevonden</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% else %}
                {% for registration in registrations %}
                    {% if registration.user.id == user.id %}
                        <tr>
                            <td>{{ registration.lessonId.date  ? registration.lessonId.date|date('Y-m-d') : '' }}</td>
                            <td>{{ registration.lessonId.time  ? registration.lessonId.time|date('H:i') : '' }}</td>
                            <td>{{ registration.lessonId.location }}</td>
                            <td>{{ registration.lessonId.trainingId.naam }}</td>
                            <td>{{ registration.lessonId.trainingId.costs }}</td>
                            <td>
                                {% if registration.payment == true %}
                                    <button class="btn btn-outline-success">Betaalt</button>
                                {% else %}
                                    <button class="btn btn-outline-warning">Niet betaalt</button>
                                {% endif %}
                            </td>
                        </tr>
                    {% elseif registration.user.id != app.user.id %}
                    {% else %}
                        <tr>
                            <td colspan="6">Niks gevonden</td>
                        </tr>
                    {% endif %}
                {% else %}
                    <tr>
                        <td colspan="6">Niks gevonden</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>



    {% if "ROLE_USER" in user.roles %}
        <a type="button" class="btn btn-outline-success"
           href="{{ path('adminuser_index') }}">terug</a>
    {% elseif "ROLE_INSTRUCTEUR" in user.roles %}
        <a type="button" class="btn btn-outline-success"
           href="{{ path('admininstructeurs') }}">terug</a>
    {% endif %}


    {#    <a href="{{ path('user_index') }}">back to list</a>#}

    <a type="button" class="btn btn-outline-warning"
       href="{{ path('adminuser_edit', {'id': user.id}) }}">edit</a>

    {#    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>#}

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}